AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template For ECR repository
Resources:
  LambdaImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "western-bulk"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
